version: "2"
services:
        coap:
                environment:
                        - POSTGRES_PASS
                build: .
                devices:
                        - "/dev/ttyACM0:/dev/ttyACM0"
                ports:
                        - "5000:5000"
                depends_on:
                        - "postgres"
        postgres:
                image: "postgres:9.2"
                ports:
                        - "5432:5432"
